### ISSUE TITLE
Add Find Marker genes

### ISSUE THREAD

**Issue by scootermorris** [RBVI/scNetViz#10]
We should add the capability to find marker genes for each cluster.  The marker genes should be shown in the network as larger diamonds.

**Comment by scootermorris** [comment]
So, am I missing something or are the marker genes essentially the same as the set of genes we use for the heatmap?

**Comment by AlexanderPico** [comment]
Right. `FindMarkers()` is just DE with some pre-filtering based on threshold, e.g.:

- pct.1|2 = 0.1. (same in scNetViz)
- logfc = 0.25 (set to 0.5 in scNetViz... same as scNetClust?)
- min.cells.group = 3 (not sure if we're checking this?)


https://www.rdocumentation.org/packages/Seurat/versions/3.1.0/topics/FindMarkers

I think the main point here is just to expose the fact that scNetViz has calculated "markers" and can display them to users as such. It's a major function in Seurat and, for better or for worse, folks now refer to "top DE genes" as "markers" in the context of single cell analysis.

**Comment by scootermorris** [comment]
We now add a new column to each cluster the ranks the genes by absolute fold change.  We agreed to use this in lieu of a "marker gene" approach to avoid the somewhat ambiguous (and often incorrect) use of the term "marker gene".
