### ISSUE TITLE
Violin plots per gene

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#12]
Analogous to the gene views on cell plots, the view of Violin plots per gene are also useful for visualizing marker genes. See screenshot from tutorial. Here is the VlnPlot function in Seurat:

- desc: https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/VlnPlot
- code: https://github.com/satijalab/seurat/blob/master/R/visualization.R#L518

We might want to implement this as a pulldown button with autocomplete for gene names. Both category and gene selections are required inputs.

![Screen Shot 2019-08-26 at 4 25 57 PM](https://user-images.githubusercontent.com/1418193/63730065-81935000-c81e-11e9-8e8c-61dab52746e6.png)

**Comment by scootermorris** [comment]
Done in the latest check-in.  Go to the differential expression tab, select a gene, and then look for Violin (gene) in the View Plots pull-down.
