### ISSUE TITLE
latest plotting/clustering issues plus a few UI suggestions

### ISSUE THREAD

**Issue by elainecmeng** [RBVI/scNetViz#13]
scNetViz issues 9/4-5/2019

Functionality:
- Graph layout, t-SNE (on server), Louvain, and Leiden parameter dialogs
  do not have the "Advanced preprocessing parameters" section.
  Are they supposed to? I thought all the server plotting/clustering
   was supposed to have that section based on our discussion.
  These four types of calculations also don't seem to be working...
  I just get a the red circle with white horizontal line.
  Tested on E-MTAB-7365, default category cluster k=5.

- for this same experiment, UMAP plot worked.  Then I tried t-SNE (local), which
  also seemed to work, but the plot was labeled UMAP and looked different
  than the one I got when I actually chose to run UMAP. The adjacent button
  still said "View UMAP". Just to doublechek, I ran UMAP again, and again
  the plot looked very different in the arrangement of dots, as it had when
  I first ran UMAP.  So I think the graph labels are wrong for local t-SNE.

- is there a way to reset to factory defaults after changing Settings?

- canceling is very slow, which seems weird, but maybe can't be avoided

Interface:
- under Apps->scNetViz-> capitalize "Show Experiment Tables" to parallel others

- in Advanced preprocessing parameters:
"Minimum number of cells expressed by a gene" -> "Minimum number of cells/gene"
  (since genes don't express cells)

- Add Category menu in experiment table: remove "Calculate" from the
clustering choices to parallel Add Category choices under the main menu

- experiment table DiffExp tab has "Create Network" button, maybe change to
  "Create Networks" to match the buttons in experiment browser and Results Panel

- "Import from file" dialog does not indicate required file types:
  For an experiment, as far as I know it has to be a zip, tar.gz, tgz, or gzip
  file of the three MatrixMarket files: mtx,mtx_cols,mtx_rows.
  I tried opening just the mtx to see what would happen, and it didn't give an
  error but a blank experiment table.
  For adding a category, dialog says CSV, but TSV is also accepted.

**Comment by AlexanderPico** [comment]
I've seen the local tSNE plot named a variety of things on repeated attempts: 

- null Plot
- tSNE Plot
- Graph Plot

**Comment by scootermorris** [comment]
OK, I *think* I have this fixed.  It should always be the plot type of your last calculation, now.
