### ISSUE TITLE
Initial Dim for server tSNE

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#14]
Currently = 0.  Should it be 10 by default to match local tSNE?

Suggested fix in screenshot:
![Screen Shot 2019-09-06 at 1 05 35 PM](https://user-images.githubusercontent.com/1418193/64458275-c08c9580-d0a9-11e9-9c12-a7806f55a1cb.png)

**Comment by scootermorris** [comment]
I think not, although in looking at the code, a default of 0 is probably wrong also.  In scanpy, if I set n_dims to None, it seems to do pretty well.  Currently, that's what 0 initial dimensions does.  However, it's also possible to set n_dims to 0, which means explicitly "don't do pca".  I'm thinking that we should set the default to "-1", which would be equivalent to None and allow users to set it to 0 if they want to avoid doing pca.  Our internal implementation doesn't have the "None" option, although 0 also skips PCA.

**Comment by AlexanderPico** [comment]
Ah, okay. I wasn't sure which one was correct. So then it should be 0 (or -1) for local tSNE as well? Or is there a reason they are different default values?

**Comment by scootermorris** [comment]
Pretty different code paths.  The local version *always* uses PCA if the number of categories is > the number of initial dimensions.
