### ISSUE TITLE
Repeated clustering leads to broken pulldown

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#15]
I ran Louvain twice (with different parameters) and ended up with a pulldown that only let me select one. Need a suffix on duplicate names?
![Screen Shot 2019-09-06 at 1 29 47 PM](https://user-images.githubusercontent.com/1418193/64458563-8a034a80-d0aa-11e9-9df2-0ec6381d9602.png)

**Comment by scootermorris** [comment]
OK, now fixed.
