### ISSUE TITLE
Gene selection for violin (gene) not registering sorting

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#16]
Steps to reproduce:

1. Get to DiffExp
2. Note the name of the top gene
3. Sort by anything other than Gene
4. Seelct top gene, then view violin (gene)

Expected: violin plot of selected gene
Obs: vioing plot of gene in same position as selection, but from Gene-sorted list.

**Comment by scootermorris** [comment]
Fixed.
