### ISSUE TITLE
Settings doesn't have FDR cutoff, node rank columns empty

### ISSUE THREAD

**Issue by elainecmeng** [RBVI/scNetViz#23]
scNetViz comments 9/10/2019

- icons look great, thanks Alex!

- Help button on experiment browser (both SCEA and HCS) goes to preview URL

Settings dialog, Network creation settings:
- pValue 0.05 and and Top n genes 0E0 still appear here, FDR cutoff does not (or maybe it's just a matter of text labeling, "pValue" should be "FDR"?)

Results Panel, Enrichment:
- maybe "FDR cutoff" is no longer needed in this section since an FDR cutoff is already used for network generation

Cytoscape Node Table:
- "scNetViz Cluster N Rank" columns are blank except for the largest N
  (e.g. only for cluster 5 using E-MTAB-7365 category k=5, the default)

**Comment by scootermorris** [comment]
Fixed help button and settings dialog.  FDR cutoff is still needed -- it's the FDR for enrichment, which is not the same as the FDR for the expression values used for the network generation.

Working on the rank stuff now.

**Comment by scootermorris** [comment]
The ranking stuff was working -- just needed to select the correct network.
