### ISSUE TITLE
Categories table rotation with save/restore session

### ISSUE THREAD

**Issue by elainecmeng** [RBVI/scNetViz#25]
After using scNetViz 1.0.1 on E-GEOD-84465 (which dataset probably doesn't matter) all the way through network generation, I saved a session.  When I restored the session, the Categories table was rotated, so that what had originally been the lefthand column became the  column headings.  I have the session but it may be too big to attach.

Original:
![Screen Shot 2019-10-17 at 2 39 26 PM](https://user-images.githubusercontent.com/54961936/67053206-7f9a8e80-f0f5-11e9-8b86-f8130e77d579.png)

After session restore:
![Screen Shot 2019-10-17 at 3 46 06 PM](https://user-images.githubusercontent.com/54961936/67053112-43672e00-f0f5-11e9-8d30-0264beeb4ac5.png)

**Comment by elainecmeng** [comment]
This has the side effect of showing the wrong thing under "Comparison" in the DiffExp tab, namely the identifier of some cell, SRRNNNNNNNN

**Comment by AlexanderPico** [comment]
Ah, I think Scooter updated the category importer to transpose since the files from EBI come in the wrong shape. However, the same importer might be used to read in serialized tables from session to session. I bet if you save and restore again, it might be flipped again! :)

**Comment by elainecmeng** [comment]
Haha, that does work!  Thanks also for assigning and labeling the issue for me.  Apologies, I'm a github newbie and haven't figured out the MO.

**Comment by scootermorris** [comment]
This should be fixed, now.
