### ISSUE TITLE
command line option to create network in one step

### ISSUE THREAD

**Issue by dataMaster-Kris** [RBVI/scNetViz#27]
Hi,

In Cytoscape GUI, there is an option in the Single Cell Expression Atlas Browser to "Create Networks", which performs differential analysis and fetches networks directly in one step. I could not find an equivalent command line option. It will be good to have this. Also, it will be good if the command allowed changing the default settings.

**Comment by scootermorris** [comment]
Done, except that you need to load the experiment first.  So, to create everything for E-CURD-7, you would need to do:
scnetviz load gxa experiment accession="E-CURD-7"
scnetviz create all experiment="E-CURD-7"
