### ISSUE TITLE
Bug in function to add category from file

### ISSUE THREAD

**Issue by dataMaster-Kris** [RBVI/scNetViz#29]
I ran into a weird issue with loading data from a file for analysis using scNetViz. I downloaded the E-MTAB-5553 data from the EBI website. The files can be downloaded [here](https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-5553/downloads). I loaded the file named E-MTAB-5553-normalised-files.zip using **Apps→scNetViz→Load Experiment→Import** from the file option from the menu. Then, I used the **Add Category** option to load E-MTAB-5553.clusters.tsv. I ran DiffExp for the line with TRUE value but **Create networks** gave me an error. I found out that the reading of E-MTAB-5553.clusters.tsv was not proper -- the column with K values had been deleted but the column title K was present and had been shifted to the next column. Due to this, the differential expression results were not significant for any gene and "create networks" threw an error. I tried several ways to troubleshoot but none worked.

**Comment by khanspers** [comment]
I see this too. But it looks like "Sel.K" is still there but the values from K columns disappeared and everything got shifted to the left. 
<img width="497" alt="Screen Shot 2020-10-22 at 5 00 33 PM" src="https://user-images.githubusercontent.com/1442197/96941815-4de6a100-1488-11eb-8a28-3514135ca78d.png">

**Comment by scootermorris** [comment]
OK, I think this is now fixed.
