### ISSUE TITLE
list and show functions

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#3]
I'm not sure I understand these completely... here are my observations so far:

1. list gxa entries - list all experiments from EBI (same as list from initial app launch). The returned JSON is odd (see other issue: Defaults for 'list gxa entries' #4 )
2. list experiments - list of loaded experiments? You can load more than one experiment at a time? Do we want this? How does a user unload an experiment? Will this lead to memory issues?
3. show experiment - shows details for a specified accession, but only for previously loaded experiments
4. show experiment table - pops up table for specified accession of previously loaded experiment

**Comment by RBVI** [comment]
1. I'll look at that...
2. Yes, we can have multiple experiments loaded.  Architecturally, I think that's the right thing, although we might want to disable the feature by internally calling remove experiment when a new experiment is loaded.  My thought was that we would add a menu item to remove an experiment.
3. That's correct, the idea is to show details for a loaded accession.  We might not have all of the information we need if we haven't loaded the experiment.
4. Correct.

**Comment by AlexanderPico** [comment]
Ok. 3 and 4 makes sense. 2 is fine if we add 'remove experiment'.  And 1 is not about the JSON output (my mistake), it's about the defaults, I think. See Issue #4.
