### ISSUE TITLE
calculate UMAP and tsne do not display any plots

### ISSUE THREAD

**Issue by dataMaster-Kris** [RBVI/scNetViz#30]
When I ran `scnetviz calculate UMAP` and `scnetviz calculate tsne` using RCy3, I was expecting to see the plots. Instead, all I got was "D@c70ec9b" printed in R output. Checking the status of cytoscape tasks suggests that the calculations are successful. Is it deliberate that no plots are being displayed?

**Comment by scootermorris** [comment]
OK, this is fixed (sort of).  First, I cleaned up the return value, so you get a more reasonable result.  If you are coming in via CyREST, you should now get a JSON return with the actually x,y coordinates of the embedding (please check this).  I also added a new command to show the plot: scnetviz show cell plot.

**Comment by dataMaster-Kris** [comment]
The plotting command works, i.e., the plot is displayed in the Cytoscape session but the command only prints "Complete" in the R session. 

My command was:

`RCy3::commandsRun('scnetviz show cell plot accession=E-GEOD-109979 category=E-GEOD-109979.clusters.tsv categoryRow=0')`

**Comment by scootermorris** [comment]
I'll take a look at why you aren't getting the proper return value.

**Comment by scootermorris** [comment]
OK, that's actually the correct behavior.  calculate cell plot will return the x,y coordinates, but show cell plot should only show it.  Do you get the x,y coordinates with the calculate cell plot?

**Comment by dataMaster-Kris** [comment]
> OK, that's actually the correct behavior. calculate cell plot will return the x,y coordinates, but show cell plot should only show it. Do you get the x,y coordinates with the calculate cell plot?

The commands are behaving as I expect. `calculate cell plot` does not return anything in the R session. In one of your previous comments, you wrote

> If you are coming in via CyREST, you should now get a JSON return with the actually x,y coordinates of the embedding (please check this).

I am guessing that using RCy3 package does not amount to coming in via CyREST, right?

**Comment by AlexanderPico** [comment]
Try `commandsPOST` instead of `commandsRun`. They both go through CyREST, but POST will process the return differently than Run (which is GET).

You can also test the function and see the return in the Swagger docs for Commands API. This is a good way to see if the expected return is not coming back due to Cytoscape/CyREST or due to RCy3.  If the latter, then I should be able to fix RCy3 to return the result coming back via CyREST.

**Comment by dataMaster-Kris** [comment]
Cool, that works.
