### ISSUE TITLE
categoryRow listed as optional on Swagger but RCy3 seems to require it

### ISSUE THREAD

**Issue by dataMaster-Kris** [RBVI/scNetViz#32]
When I run `scnetviz calculate diffexp` without specifying categoryRow, I get "Unable complete differential expression calculation: Index -1 out of bounds for length 7". However, the Swagger documentation says that categoryRow is optional.

**Comment by scootermorris** [comment]
It is optional, but only if the category has a default row.  So, for GXA, almost all of the experiments have a default clustering value, but there is no default for Design/Factors.
