### ISSUE TITLE
Is it possible to initialize with PCA embedding for the t-SNE and UMAP cell plots?

### ISSUE THREAD

**Issue by dataMaster-Kris** [RBVI/scNetViz#35]
[This article](https://www.nature.com/articles/s41467-019-13056-x) proposes PCA initialization to improve the t-SNE and UMAP embeddings. Is this what the implementation in scNetViz does?

**Comment by scootermorris** [comment]
Yes -- just set the number of dimensions to 0 and it will do a PCA before t-SNE.  scanpy's UMAP implementation doesn't provide that capability.
