### ISSUE TITLE
Defaults for 'list gxa entries'

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#4]
If I run list gxa entries in the Automation Panel or Swagger, it works fine without 'assay' or 'species' parameter specified. However, if I run it via RCy3 then I get the standard message:  "Available arguments for ... ".

I'm not sure why the defaults aren't working for this method. This has worked in the past for other optional args. Is there anything you are doing differently here in terms of how and when the defaults are defined?

**Comment by RBVI** [comment]
Very strange.  No, I'm not doing anything different, as far as I know.  Are you seeing any tracebacks?

**Comment by AlexanderPico** [comment]
It's not an error. I'm getting a response as if I requested 'help', which is what the GET function does by default.  The heart of the problem is that I use GET for commandsRun, which works fine for all the GET and POST commands we've come up with so far... until this one. I can instruct folks to use commandsPOST for just this one case, but that seems clunky. And I can't switch commandsRun to always use POST because some commands are GET...

For example, if I specify a species, then it works fine with commandsRun. That's why I suspect that the defaults just are quite working the same.

**Comment by RBVI** [comment]
But you don't see a traceback?  I have an idea what might be going on, but I've got to run an errand.  Can you send me an R snippet so I can reproduce it?

**Comment by AlexanderPico** [comment]
Right, no traceback. Here are the R commands to reproduce:

```
library(RCy3)

commandsRun('scnetviz list gxa entries') #this runs GET and returns a standard response about missing args

commandsPOST('scnetviz list gxa entries') #this works, but is not ideal in terms of documentation/training

commandsRun('scnetviz list gxa entries species=""Homo sapiens"') #this works fine and is my current workaround

**Comment by scootermorris** [comment]
Short answer: I have no idea.  It works just fine using commandsPOST, as you point out.  I've made a bunch of changes, but no joy.  I think we'll need to push this off to David.

**Comment by AlexanderPico** [comment]
Do you know why these results are different?

commandsRun('scnetviz list gxa entries species=""Homo sapiens"')
commandsPOST('scnetviz list gxa entries species=""Homo sapiens"')

Observations: 
1. POST does not apprear using the species arg
2. The returned data structures are different

**Comment by scootermorris** [comment]
1. That's a bug that I just fixed
2. Really?  I'll take a harder look at that.  They should be identical

**Comment by AlexanderPico** [comment]
Re: 2, maybe it's how I'm parsing the GET vs POST results in RCy3... Sorry, I should know what those are doing! :)

**Comment by scootermorris** [comment]
I think the GET returns text rather than JSON...
