### ISSUE TITLE
Retrieve Table Only Works Once

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#9]
The "Retrieve Table" button in the results panel works the first time, but subsequent attempts fail.

Steps to reproduce:
1. load your favorite mtx from EBI
2. create networks however you like
3. select a network with pos and neg nodes
4. choose "Positive only" and retrieve table (works fine)
5. choose "Negative only" and retrieve table

Obs: 
 * No new table retrieved
 * Error in status bar: Command string show enrichment isn't available
 * All nodes are selected

Workaround:
 * select the correct nodes and use menu: Apps>String enrichment>retrieve table

**Comment by scootermorris** [comment]
Fixed.
